[workspace]

members = [
    "crates/circuit",
    "crates/cli",
]

default-members = ["crates/cli"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"
